path_length = 8.75  # mm
wavelength = 1550  # nm
n0 = 2.8  # refractive index
r41 = 5.5  # 1e-12 m/V electro-optic coefficient

crop_y0 = 145  # pixels
crop_y1 = 520  # pixels
crop_x0 = 210  # pixels
crop_x1 = 320  # pixels

box_left = 14
box_right = 361
box_top = 23
box_bottom = 87
